### ISSUE TITLE
Max Length for Malaysia is wrong

### ISSUE THREAD

**Issue by vaulient** [vanshg395/intl_phone_field#101]
The current max length is 9 when it should be 11, is there any way for me to manually change the max length?

**Comment by marcaureln** [comment]
Fixed by 0c2b3fc. But the fix will be available within the next release, nonetheless if it urges, you can use this in your pubspec.yaml file :
```dependencies:
  intl_phone_field:
    git:
      url: git://github.com/vanshg395/intl_phone_field.git
```
Refers to this [page](https://flutter.dev/docs/development/packages-and-plugins/using-packages) for more details
