### ISSUE TITLE
Unable to load asset: packages/intl_phone_field/assets/flags/us.png

### ISSUE THREAD

**Issue by RahulMachhiC** [vanshg395/intl_phone_field#102]

**Comment by CrayTexas2018** [comment]
For anyone having this issue, make sure you're on the latest version of the widget. Pub says 2.0.1 but it should be 2.1.0

**Comment by rcsousa14** [comment]
have the latest version 3.1.0 still having this problem

**Comment by marcaureln** [comment]
Hey @rcsousa14 can you provide further details to help us reproduce your issue and understand want is going on. I haven't yet experienced this issue. So, give us the output of your `flutter doctor -v`, your `pubspec.yaml` and a piece of code. Thereafter I'll reopen the issue and investigate. Thanks
