### ISSUE TITLE
How to change cursor color?

### ISSUE THREAD

**Issue by rafaelsimonassi** [vanshg395/intl_phone_field#109]
Hello, 

The cursor color always pick the ThemeData.primarySwatch color. 
Is it possible to override the cursor color of the IntlPhoneField component?

Regards,

**Comment by marcaureln** [comment]
Hi, You cannot do it now. But, hopefully you'll be able to do it in coming release (parameter added with 29b40b2)
Nevertheless, you can use (carefully) the GitHub version of the package, see how [here](https://stackoverflow.com/questions/54022704/how-to-add-a-package-from-github-in-flutter#54023220)

Best
