### ISSUE TITLE
Align country selector with the text field when in a textfield container

### ISSUE THREAD

**Issue by MikeMudimba** [vanshg395/intl_phone_field#117]
![image](https://user-images.githubusercontent.com/82000523/134440101-5d07d325-dcbe-4756-9745-a9f30fdd7e9a.png)

**Comment by marcaureln** [comment]
You'll be able to do this with the next package's version

**Comment by aleksandar-radivojevic** [comment]
This still isnt fixed in current stable version of plugin.

**Comment by heshesh2010** [comment]
you can wrap your widget with Directionality like this :

` Directionality(
            textDirection: TextDirection.ltr,
            child: IntlPhoneField(
                key: key,
                onSaved: onSaved,
                onChanged: onChanged,
                initialValue: initialValue ?? '',
                initialCountryCode: initialCountryCode ?? 'SA',
                showDropdownIcon: false,
                pickerDialogStyle: PickerDialogStyle(
                    countryNameStyle: Get.textTheme.bodyText2),
                style: style ?? Get.textTheme.bodyText2,
                textAlign: textAlign ?? TextAlign.end,
                disableLengthCheck: false,
                autovalidateMode: AutovalidateMode.disabled,
                decoration: InputDecoration(
                  hintText: hintText ?? '',
                  hintStyle: Get.textTheme.caption,
                  floatingLabelBehavior: FloatingLabelBehavior.never,
                  contentPadding: EdgeInsets.all(0),
                  border: OutlineInputBorder(borderSide: BorderSide.none),
                  focusedBorder:
                      OutlineInputBorder(borderSide: BorderSide.none),
                  enabledBorder:
                      OutlineInputBorder(borderSide: BorderSide.none),
                  suffixIcon: suffixIcon,
                  suffix: suffix,
                  errorText: errorText,
                )),
          )`
