### ISSUE TITLE
Incorrect validation

### ISSUE THREAD

**Issue by zmeggyesi** [vanshg395/intl_phone_field#12]
The current validation expects _exactly_ ten digits, which is not universally correct. According to E.164, there might be _up to_ 12 digits in the number, but possibly less.

**Comment by vanshg395** [comment]
Duplicate of #6

**Comment by zmeggyesi** [comment]
That is not true.

The `maxLength` argument only deals with that, the _maximum length_, but it cannot handle phone numbers that are _shorter_ than said length. For instance, the perfectly valid phone number of +3612345678 (yes, this is a real and existing number) would be rejected after being parsed as `36` for the country code and `1 234 5678` for the number, which is only 8 digits but valid nonetheless. Additionally, this is a _landline number_, but the validation message is hardcoded to state a _mobile_ number.

Please see the newly-created PR with the minimum necessary code change to correct the validation process.
