### ISSUE TITLE
Error on max length of Cameroon phone number

### ISSUE THREAD

**Issue by cesairekent** [vanshg395/intl_phone_field#126]
Now max length of phone number in cameroon is 9
Ex : (+237) 699887755

please update package.

thank!

**Comment by wutsi** [comment]
Any one maintaining this repo?

**Comment by cesairekent** [comment]
I don't know

**Comment by lingster** [comment]
looks like this has been fixed in commit 0f9add / #127

**Comment by cesairekent** [comment]
yes I had made a commit for that.
