### ISSUE TITLE
phone number field and dropdown ui is inconsistent

### ISSUE THREAD

**Issue by guptan404** [vanshg395/intl_phone_field#129]
Phone number field and dropdown ui is inconsistent when we type phone number its typed on the top of text field and dropdown is down

![Screenshot_1634739235](https://user-images.githubusercontent.com/28225683/138110151-1086bcc9-7a6f-4965-8492-e04f2f73d672.png)

**Comment by marcaureln** [comment]
You won't have any alignment issue with the 3.0.0

**Comment by danielSafeNow** [comment]
I have the exact issue on 3.0.0
