### ISSUE TITLE
countries information wrong

### ISSUE THREAD

**Issue by joke0ck** [vanshg395/intl_phone_field#135]
countries.dart => "code": "HK" =>  max_length is 8 ,not 9

**Comment by arjundevlucid** [comment]
Cyprus countries length is  8 digits without country code. Please fix @vanshg395 .

**Comment by marcaureln** [comment]
The Hong Kong and Cyprus countries length have been update with #103 and #137 PRs respectively. Stay tuned for the upcoming release.
