### ISSUE TITLE
add support for region codes

### ISSUE THREAD

**Issue by lingster** [vanshg395/intl_phone_field#138]
For some countries, the initial prefix used is not specific enough to be able to look up the actual country, eg: 

https://en.wikipedia.org/wiki/List_of_country_calling_codes

+44 –  United Kingdom
    +44 1481 –  Guernsey
    +44 1534 –  Jersey
    +44 1624 –  Isle of Man

So this attached PR is to add a regionCode so more specific countries can be correct identified. 

This will allow allow the widget to correctly select the country flag when the widget is initialised by a completePhoneNumber

**Comment by daniil-shumko** [comment]
@vanshg395 do you think this can be added any time soon? We are trying to use this in a project where we need the region to be recognised correctly.
