### ISSUE TITLE
Cant get updated country code if a user changes phone number and then changes the country code from drop down.

### ISSUE THREAD

**Issue by iamwaseemsh** [vanshg395/intl_phone_field#141]
+91 is default country code, I typed phone number 123 in phone input field, then in onChange function i got value **+91123** , now suppose here i change the country code to +92 then onchange method wont be triggered, it only triggers when we type something in phone input field. Now in controller.text i will get +91123 although i should get +92123.

**Comment by marcaureln** [comment]
To track country code change, use the `onCountryChanged` callback, `onChanged` only takes care of the text field, since the `IntlPhoneField` widget is the combination of two distinct widgets, a `TextFormField` and a custom country selector. Hope that helped you.
