### ISSUE TITLE
initialValue == null || controller == null not equal to true

### ISSUE THREAD

**Issue by nikhilArhamLabs** [vanshg395/intl_phone_field#146]
Hello
 I am using the latest version of this package and i am facing this issue initialValue == null || controller == null not equal to true.
But i am initializing my controller and still this issue is persists.
I am using latest flutter stable channel and my dart sdk is 2.14.0.
If i make my controller nullable then how i use the controller values? The previous version was perfectly fine fine with the controller feature but because of this issue i have to downgrade the version.
Please resolve this issue as soon as possible.
Thank you :)

**Comment by suhail600** [comment]
same issue cant assign controller ,even if initial value is not specified

**Comment by suhail600** [comment]
found a new way , bro get inside the package and remove all the items with initial value, then we can assign controller, and using controller we can assign initial value

**Comment by nikhilArhamLabs** [comment]
Hello,

Yes it is fixed thank you so much for releasing this and fixing this issue.
Great work man and God bless you always :)
