### ISSUE TITLE
phone number validation

### ISSUE THREAD

**Issue by yusuf-umar** [vanshg395/intl_phone_field#147]
hi,  please i am trying to check if the input phone number is empty, how can i do that please. thanks

**Comment by skanderhamdi** [comment]
For empty:
onChanged: (value) => setState((){ empty = value.isEmpty; }),

For validation:  **validator** property fired only when user fill the field with a valid phone number
validator: (value) => setState((){ valid = true; }),

**Comment by skanderhamdi** [comment]
Better:

`import 'package:intl_phone_field/countries.dart';`
....
```
onChanged: (phoneNumber) {
   Country country = countries.firstWhere((element) => "+${element.dialCode}" == phone.countryCode);
  if(phone.number.length == country.maxLength || phone.number.length > country.minLength && phone.number.length < country.maxLength)
                      {
                             phoneValid = false;
                      }
}
```

**Comment by tuutaii** [comment]
Hi, i'm trying to hide the country code and custom a circle flags. How can i do that . Thanks

**Comment by nadous** [comment]
If I may, that's a little confusing since a common use-case would be to :

1. Embed the input in a wider form ;
2. Set `autovalidateMode` to `AutovalidateMode.disabled` ;
3. Validate the form using a `GlobalKey<FormState>`.

Giving the fact that the `validator` parameter of the internal `TextForrnField` isn't exposed, we can't replicate that behavior. I came out to refactor the `validator` member to `onChangedValidator` (since it really is used there) and add a `validator` parameter  that is actually passed to the `TextForrnField`, all that allowing the wrapping `Form` to be validated on demand. Not the cleanest option though…

**Comment by remymumoh** [comment]
what is the best way to do validation?
 ```
  validator: (value) {
                                      if (value == null || value.isEmpty) {
                                        return 'Please Enter Your Phone No';
                                      }
                                      return null;
                                    },
```
this doesnt work

**Comment by zitob9** [comment]
+1 i have the same problem

**Comment by marcaureln** [comment]
> what is the best way to do validation?
> 
> ```
>  validator: (value) {
>                                      if (value == null || value.isEmpty) {
>                                        return 'Please Enter Your Phone No';
>                                      }
>                                      return null;
>                                    },
> ```
> 
> this doesnt work

This, will work in 3.1.0 :
```
validator: (PhoneNumber value) {
  print('in widget validator');
  if (value == null || value.number.isEmpty) {
    print('Please Enter Your Phone No');
    return 'Please Enter Your Phone No';
  }
  return null;
},
```
But, it's not necessary. The default validator will be trigger now (fccd1e2).

**Comment by remymumoh** [comment]
Thank you, I was forced to fix the library for my self, but glad it was updated

**Comment by remymumoh** [comment]
> > what is the best way to do validation?
> > ```
> >  validator: (value) {
> >                                      if (value == null || value.isEmpty) {
> >                                        return 'Please Enter Your Phone No';
> >                                      }
> >                                      return null;
> >                                    },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this doesnt work
> 
> This, will work in 3.1.0 :
> 
> ```
> validator: (PhoneNumber value) {
>   print('in widget validator');
>   if (value == null || value.number.isEmpty) {
>     print('Please Enter Your Phone No');
>     return 'Please Enter Your Phone No';
>   }
>   return null;
> },
> ```
> 
> But, it's not necessary. The default validator will be trigger now ([fccd1e2](https://github.com/vanshg395/intl_phone_field/commit/fccd1e2ffd3a2eb71878052079e0252d4740af4d)).

you have not pushed this to pub.dev

**Comment by pol9kov** [comment]
Can't trigger validation by outside. I do like this https://www.topcoder.com/thrive/articles/form-validation-in-flutter .
Do only I have this issue?
