### ISSUE TITLE
Getting extra spacing in bottom side.

### ISSUE THREAD

**Issue by panchalAlpit** [vanshg395/intl_phone_field#157]
I'm getting extra padding in bottom side. I have attached the screenshot and code.
I have used the latest plugin: intl_phone_field: ^3.0.1.

![processed-7b4f6bde-e38f-416f-98ec-707e10c464a3_zVUwMALl](https://user-images.githubusercontent.com/48007084/156778684-266f9cb9-b54d-4ba4-b02e-f53dfcb2f950.jpeg)

      `Container(
          padding: EdgeInsets.only(left: 5,right: 5),
          decoration: BoxDecoration(
              color: Colors.greenAccent,
              borderRadius: BorderRadius.circular(8)
          ),
          child: IntlPhoneField(
            textAlignVertical: TextAlignVertical.center,
            decoration: InputDecoration(
                contentPadding: EdgeInsets.zero,
                isCollapsed: false,
                isDense: true,
                counter: Container(),
                hintText: B_String.Mobile_Number,
                hintStyle: _hintStyle(),
                border: OutlineInputBorder(
                  borderSide: BorderSide.none,
                ),
                errorText: "eds dsf"
            ),
            initialCountryCode: "IN",
            showCountryFlag: false,
            dropdownIconPosition: IconPosition.trailing,
            dropdownIcon: Icon(Icons.keyboard_arrow_down_rounded,color: BColors.DM_App_Colors_dark,size: 25,),
            onChanged: (phone) {
              print(phone.completeNumber);
            },
            onCountryChanged: (value){

            },

          ),

        )`
        
        
        
        [✓] Flutter (Channel stable, 2.10.0, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.10.0 at /Users/i-lanamtechnologies/Documents/Softwere/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (4 weeks ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/i-lanamtechnologies/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

**Comment by agrawalsurabhi89** [comment]
any solution for this, even i'm facing this issue

**Comment by panchalAlpit** [comment]
@agrawalsurabhi89 Still facing the issue.
