### ISSUE TITLE
IntlPhoneField Firebase

### ISSUE THREAD

**Issue by xTheMasters** [vanshg395/intl_phone_field#159]
Hello I try to save the input phone number + code into a firebase data but i cant set my controller to onchanged or into controller
 any idea how i can implemented?

I got this msg

The argument type 'void Function(String)' can't be assigned to the parameter type 'TextEditingController?'.

**Comment by AndriiHarashchak** [comment]
This error occurs because you trying to assign some function instead of TextEditingController. check your code and provide the correct object.

**Comment by xTheMasters** [comment]
> This error occurs because you trying to assign some function instead of TextEditingController. check your code and provide the correct object.

Thanks I got it, mmm now how I can get the number from firebase, when i get it in profile page, i see the complet number in the filed and the initial default code value ☹️

**Comment by marcaureln** [comment]
You should provide code example, to help us assist you. I'm closing because @AndriiHarashchak kinda answer your initial request and because the issue stall too. Feel free to open a new issue, with detailed information and code example.
