### ISSUE TITLE
Initial value field does not work

### ISSUE THREAD

**Issue by Kiwi-KiwiCorp** [vanshg395/intl_phone_field#164]
I cannot figure out why but the initial value field does not seem to do anything. You can get around this by changing the text value on the TextEditingController you pass in however unfortunately if you pass back in the value this field spits out you will end up with the prefix as well. So for example if you enter +44 - 7476876876 when creating a record and then you come back to the same form to edit that record. If you set the text editing field to the output it ends up showing +44 - +447476876876. It would be nice if the initial value field parsed the input so that it auto-detects the +44 at the start of the number and therefore selects that in the dropdown for you before removing it from the phone number. At the moment, I'm thinking I'm going to have to do this manually.

**Comment by xTheMasters** [comment]
I had the same problem ☹️ u fix it?
