### ISSUE TITLE
Validator cannot be override

### ISSUE THREAD

**Issue by MarVills** [vanshg395/intl_phone_field#171]
When I set validator in phone field :
validator: (val) {
      if (val == "") {
          return "Phone number is required";
      } else {
         return null;
      }
},
The validator won't validate. Only the onChange default validator message "Invalid Mobile Number" works when you type something on the field. What I want is that this field should validate if empty and also can use this field that allow empty field. The only thing that I cant do is I cant customize the validator. Is any one here have the solution?

**Comment by Pierre2tm** [comment]
Same problem.

**Comment by uttom41** [comment]
same problem

**Comment by ged-flod** [comment]
same problem.

**Comment by fisforfaheem** [comment]
please fix :(
