### ISSUE TITLE
The size of flag and country code is too big!

### ISSUE THREAD

**Issue by maskeyp** [vanshg395/intl_phone_field#176]
How can i resize the flag ans country code size?

**Comment by Jardynero** [comment]
> How can i resize the flag ans country code size?

Hi! For change size of country code you can use dropdownTextStyle property

`IntlPhoneField(
      controller: controller,
      initialCountryCode: 'DE',
      dropdownIcon:  const Icon(Icons.arrow_drop_down, color: AppColors.heading,),
     dropdownTextStyle: TextStyle(fontSize: 20), // change style of country code here
    );
  }`
