### ISSUE TITLE
Feature request: Remove/detect country code from initialValue

### ISSUE THREAD

**Issue by a7medpa** [vanshg395/intl_phone_field#196]
Hi,

If we can have an option that removes the country code from the initialValue and detect the country ISO used from the length and prefix, that would be awesome. 

I can imagine many people like myself are pulling data for different phone numbers and when using them as an initial value we get duplicate data. Of course, we could reg ex it with some additional helpers but it would be an amazing feature.

Example:
initialValue is +447740000000
If we have a property like 'detectCountryCode' set to true then the initial value will update to: '7740000000'
initialCountryCode would automatically be set to 'GB'.

**Comment by GujjuFlutterGuy** [comment]
@a7medpa I agree with you. I have similar case too.

If from the backend side if number is +910000000000 and I want to show this number in edit profile then there are issue that +91 is also getting added and also initialCountryCode could have updated from the number. If this is going to fix it would be really helpful.
