### ISSUE TITLE
validator not working fine

### ISSUE THREAD

**Issue by MohammadAsef** [vanshg395/intl_phone_field#198]
validator stop working when change country code it work well when user interaction but it doesn't work when we change country code or call form validate method. please fix it. thanks for your best package.

**Comment by Dennis-Mwea** [comment]
@ vanshg395  https://github.com/vanshg395/intl_phone_field/pull/206 This would solve the custom validation issue.

**Comment by MohammadAsef** [comment]
ok , thanks for response
