### ISSUE TITLE
Correct input length for Ecuador

### ISSUE THREAD

**Issue by JuanEgas** [vanshg395/intl_phone_field#204]
MaxLength = 9

**Comment by swebsas** [comment]
Same problem, in Ecuador only physical phones have 8 characters, mobiles 9

**Comment by Wladimir1097** [comment]
Ecuador! Longitud máxima = 9 por favor

**Comment by Wladimir1097** [comment]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/43644686/230999148-1f1caa6d-e1a4-4789-9c95-a547669ed9a7.png">


Ecuador! Longitud máxima  y minima = 9 por favor
