### ISSUE TITLE
Null exception when AutoValidateMode is `always`

### ISSUE THREAD

**Issue by Joeluck** [vanshg395/intl_phone_field#208]
Steps to reproduce : 

- Add an `initialValue` 
- Set `autoValidateMode` to `always`

Exception is raised.

I made the fix, @all-contributors can you please add me for contributions so I can send a PR ?

Thank you :)

**Comment by ShenoudaMikhael** [comment]
just add the validator fixes the issue:

`IntlPhoneField(validator: (p0) {return "";},
autovalidateMode: AutovalidateMode.always,
)
`

**Comment by neoacevedo** [comment]
@ShenoudaMikhael that doesn't work, the field still raises the same error:
```
The following _TypeError was thrown building _FormScope:
TypeError: null: type 'Null' is not a subtype of type 'Future<dynamic>'
```
