### ISSUE TITLE
Feature: Add support for setting the CountryCode

### ISSUE THREAD

**Issue by tjerkw** [vanshg395/intl_phone_field#21]
My app already has phone number coming from async, so i need to be able to set countryCode dynamically.
But initialCountryCode, only sets the initial value, if you change it later, the widget will NOT be rebuild.

**Comment by vanshg395** [comment]
If you set initialCountryCode to a dynamic variable and then change the value of that variable inside setState, it will work. It worked for me where I was getting countryCode from IP Address.

**Comment by stMerlHin** [comment]
How can I get country code from ip dynamically  😆?

**Comment by vanshg395** [comment]
Issue is not related to this package. Use some IP package for the purpose.

**Comment by KapilTK** [comment]
I'm trying to change the initial value after the build in initState and the value is from the local database, which is also not changing.

**Comment by debovitch** [comment]
You can add a key: UniqueKey() to your IntlPhoneField widget, it will force to pass in the initState again.

**Comment by debovitch** [comment]
You can add a key: UniqueKey() to your IntlPhoneField widget, it will force to pass in the initState again.
