### ISSUE TITLE
Run function on valid phone number

### ISSUE THREAD

**Issue by saveKenny** [vanshg395/intl_phone_field#216]
**I want to enable/disable a Submit Button, based on the package validation.**

Right now the `IntlPhoneField ` supports `onChange`, `onSubmit` and `onSaved` functions, but does not support an `onValid` function.

How do I achieve that?

**Comment by CartmanGD** [comment]
Facing the same issue..

**Comment by CartmanGD** [comment]
I solved this issue by extracting the current selected `Country` object, and use its `minLength` and `maxLength` parameters in order to detect its validity.

Checkout the full [example](https://stackoverflow.com/a/73435267/12695188) that I posted on StackOverflow.

**Comment by saveKenny** [comment]
I solved this issue by extracting the current selected `Country` object, and use its `minLength` and `maxLength` parameters in order to detect its validity.

Checkout the full [example](https://stackoverflow.com/a/73435267/12695188) that I posted on StackOverflow.

**Comment by saveKenny** [comment]
Also I consider to contribute this package by adding an `onValid` function (hopefully I will have time for that).

**Comment by saveKenny** [comment]
@jgeewax Please accept [my pull request](https://github.com/vanshg395/intl_phone_field/pull/217), so others will enjoy this feature.

**Comment by CartmanGD** [comment]
IMO a better approach would be if the `PhoneNumber` object which provided in the `onChange` function, will support the `isValidNumber` getter. Then you could statement `isValidNumber` and do as you want.

**Comment by jimmyff** [comment]
I've created a PR that resolves this issue. My approach is to add a validates parameter to the onChanged callback:

https://github.com/vanshg395/intl_phone_field/pull/286
