### ISSUE TITLE
Styling of  intl_phone_field

### ISSUE THREAD

**Issue by DevMansoor** [vanshg395/intl_phone_field#220]
![2566f9ee-2db7-40ac-a73e-d467691128fb](https://user-images.githubusercontent.com/66817501/190104873-63b89318-f6f7-4e6d-940d-bd3426ca2d2b.jpg)
How can I move label text to left side?
Here is my code:
```
IntlPhoneField(
                    decoration: InputDecoration(
                      focusedBorder: OutlineInputBorder(
                          borderSide: const BorderSide(color: AppColors.fGradient1), borderRadius: BorderRadius.circular(Dimensions.radius10 + 5)),
                      enabledBorder: OutlineInputBorder(
                          borderSide: const BorderSide(color: AppColors.fGradient1), borderRadius: BorderRadius.circular(Dimensions.radius10 + 5)),
                      focusedErrorBorder: OutlineInputBorder(
                          borderSide: const BorderSide(color: AppColors.fGradient1), borderRadius: BorderRadius.circular(Dimensions.radius10 + 5)),
                      isDense: true,
                      floatingLabelBehavior: FloatingLabelBehavior.always,
                      labelText: 'WhatsApp',
                      labelStyle: TextStyle(fontFamily: "ROCK", color: AppColors.fGradient1),
                      border: OutlineInputBorder(
                          borderSide: const BorderSide(color: AppColors.fGradient1), borderRadius: BorderRadius.circular(Dimensions.radius10 + 5)),
                    ),
                    initialCountryCode: 'AE',
                    onChanged: (phone) {},
                  ),
```

**Comment by heshesh2010** [comment]
1+

**Comment by heshesh2010** [comment]
you can wrap your widget with Directionality like this :

`Directionality( textDirection: TextDirection.ltr, child: IntlPhoneField( key: key, onSaved: onSaved, onChanged: onChanged, initialValue: initialValue ?? '', initialCountryCode: initialCountryCode ?? 'SA', showDropdownIcon: false, pickerDialogStyle: PickerDialogStyle( countryNameStyle: Get.textTheme.bodyText2), style: style ?? Get.textTheme.bodyText2, textAlign: textAlign ?? TextAlign.end, disableLengthCheck: false, autovalidateMode: AutovalidateMode.disabled, decoration: InputDecoration( hintText: hintText ?? '', hintStyle: Get.textTheme.caption, floatingLabelBehavior: FloatingLabelBehavior.never, contentPadding: EdgeInsets.all(0), border: OutlineInputBorder(borderSide: BorderSide.none), focusedBorder: OutlineInputBorder(borderSide: BorderSide.none), enabledBorder: OutlineInputBorder(borderSide: BorderSide.none), suffixIcon: suffixIcon, suffix: suffix, errorText: errorText, )), )`

**Comment by mans-oor** [comment]
> you can wrap your widget with Directionality like this :
> 
> ```
>  Directionality(
>             textDirection: TextDirection.ltr,
>             child: IntlPhoneField(
>                 key: key,
>                 onSaved: onSaved,
>                 onChanged: onChanged,
>                 initialValue: initialValue ?? '',
>                 initialCountryCode: initialCountryCode ?? 'SA',
>                 showDropdownIcon: false,
>                 pickerDialogStyle: PickerDialogStyle(
>                     countryNameStyle: Get.textTheme.bodyText2),
>                 style: style ?? Get.textTheme.bodyText2,
>                 textAlign: textAlign ?? TextAlign.end,
>                 disableLengthCheck: false,
>                 autovalidateMode: AutovalidateMode.disabled,
>                 decoration: InputDecoration(
>                   hintText: hintText ?? '',
>                   hintStyle: Get.textTheme.caption,
>                   floatingLabelBehavior: FloatingLabelBehavior.never,
>                   contentPadding: EdgeInsets.all(0),
>                   border: OutlineInputBorder(borderSide: BorderSide.none),
>                   focusedBorder:
>                       OutlineInputBorder(borderSide: BorderSide.none),
>                   enabledBorder:
>                       OutlineInputBorder(borderSide: BorderSide.none),
>                   suffixIcon: suffixIcon,
>                   suffix: suffix,
>                   errorText: errorText,
>                 )),
>           )
> ```

Nothing Happend
