### ISSUE TITLE
Phone number length not updating 

### ISSUE THREAD

**Issue by alamin-karno** [vanshg395/intl_phone_field#221]
I was using intl_phone_field: 3.0.1

This version has some minor issues, like some country phone number max length & min length is not valid for that country like Singapore, Malaysia etc.

I have figured out that I am using an old version of this package, and in the new version, those issues are solved, So I updated the package version and the pubspec.yml file. But phone length did not change in those countries yet. 

I have cleared the cache, restarted, cleaned the pub, and done many things to get the new package version. But those issue is not solved yet. Can anyone give me a solution on how to fix this?

**Comment by KomengTech** [comment]
The countries.dart file is having wrong data.. So best way is to disableLengthCheck: true..

**Comment by alamin-karno** [comment]
> The countries.dart file is having wrong data.. So best way is to disableLengthCheck: true..

Thanks, but I need to check them for validation. If I send a pull request is he accept it ??

**Comment by cr0r1** [comment]
Hi, any update?
