### ISSUE TITLE
How to add left padding in country code?

### ISSUE THREAD

**Issue by panchalAlpit** [vanshg395/intl_phone_field#224]
How to add padding before the country code?
Here is my current code below:
    
            `IntlPhoneField(
           textAlignVertical: TextAlignVertical.center,
          dropdownIconPosition: IconPosition.trailing,
          controller: edMobileController,
          decoration: InputDecoration(
              isCollapsed: true,
              filled: true,
              fillColor: Colors.white,
              border:  textField_border(),
              focusedBorder: r_border(),
              enabledBorder:r_border(),
              contentPadding: EdgeInsets.only(left: 10),
              counter: SizedBox(),
              hintText: R_String.Enter_your_mobile_number,hintStyle: TextStyle(fontSize: R_FontSize.size12,fontFamily: 
             R_FontName.Muli_SemiBold,color: R_Colors.label_color.withOpacity(0.3))
               ),
            showCountryFlag: false,
            dropdownIcon: Icon(Icons.keyboard_arrow_down_rounded,color: R_Colors.label_color,size: 25,),
            onChanged: (phone) {
             },
             onCountryChanged: (value){
             },

            )`
            
            
     Screenshot:-
     
![1664531643827](https://user-images.githubusercontent.com/48007084/193251570-605c85d8-1e39-41c2-bcd6-5567907892c1.JPEG)

I'm using the "intl_phone_field: ^3.1.0" version.
Please help me.

**Comment by Kavinkumarsimple** [comment]
Add the following property:

`flagsButtonPadding: EdgeInsets.only(left: 10),`

**Note: This works with and without country flag**


<img width="225" alt="Screenshot 2022-10-11 at 08 22 31" src="https://user-images.githubusercontent.com/74304337/194986209-b53cbc57-ce40-4229-848d-f38f63965de2.png">

**Comment by panchalAlpit** [comment]
Thank you @Kavinkumarsimple for this awesome update.
