### ISSUE TITLE
Min & Max length - Singapore

### ISSUE THREAD

**Issue by kentpiitch** [vanshg395/intl_phone_field#238]
Hi, the min & max phone/mobile number length in Singapore should be 8 not 12. Although the country.dart has been updated here but it is still 12 in Flutter Dev pub get. 
![image](https://user-images.githubusercontent.com/103365444/202404804-3f7acec9-990d-481e-9210-41e239e7b6e8.png)
![image](https://user-images.githubusercontent.com/103365444/202436056-7d748bb1-e8e2-4e59-b05f-e0e5183804af.png)
Thanks.

**Comment by marcaureln** [comment]
Shipped with #243 :rocket: Stay tuned for the upcoming release.
