### ISSUE TITLE
Country dropdown button and text field are not aligned 

### ISSUE THREAD

**Issue by fvisticot** [vanshg395/intl_phone_field#250]
I check the workaround of this issue but it does not work for me
Any idea / fix / workaround ?

Country dropdown button and text field are not aligned #91

![IMG_ABC797EE8FB7-1](https://user-images.githubusercontent.com/153679/214968604-692813eb-4ca3-464a-b468-27a6ce95160d.jpeg)

**Comment by lohitbura07** [comment]
I also have the same issue.

**Comment by ArpitSharma7898** [comment]
Facing same issue

**Comment by ramikhafagi96** [comment]
any fix for this>

**Comment by ramikhafagi96** [comment]
any fix for this?
