### ISSUE TITLE
Min Max Length - Italy

### ISSUE THREAD

**Issue by bricekams** [vanshg395/intl_phone_field#252]
Actualy min = max = 13 and it's not correct (see: [wikipedia ref](https://en.wikipedia.org/wiki/Telephone_numbers_in_Italy#:~:text=Mobile%20telephone%20numbers%20start%20with%20the%20digit%203%20and%20are%20generally%20ten%20digits%20long.%20It%20is%20still%20possible%2C%20but%20rare%2C%20to%20find%20nine%2Ddigit%20numbers%2C%20which%20were%20the%20first%20to%20be%20assigned.))

What's correct is min = 9 and max = 10

**Comment by niko047** [comment]
I confirm, I'm having the same issue and I had to manually change the lib's files locally. I would leave the Issue open, it has not yet been fixed as of today.

**Comment by marcaureln** [comment]
Fixed with #243

**Comment by marcaureln** [comment]
My bad, fixed now by 46952e7
