### ISSUE TITLE
FormField Key not initialized

### ISSUE THREAD

**Issue by Scheph-96** [vanshg395/intl_phone_field#258]
The key attribute in the TextFormField is not set, and it's a problem when we work in this way:

```
final GlobalKey<FormFieldState> formFieldKey;

IntlPhoneField(
      key: formFieldKey,
      controller: controller,
      decoration: fieldDecoration(hintText),
      inputFormatters: [FilteringTextInputFormatter.digitsOnly],
      onChanged: (phone) {
        print(phone.completeNumber);
      },
);
```

Later when we check the input validation like this `formFieldKey.currentState?.validate()` it returns `null`. Why ?
Because in the IntlPhoneField package source code

```
TextFormField(
      key: formFieldKey, // This field is not set
      controller: controller,
      decoration: fieldDecoration(hintText),
);
```

**Comment by Scheph-96** [comment]
It's said that we must open a issue before a pull but I didn't get a reply so I change the source code locally, maybe you can do the same

**Comment by dolapobabs** [comment]
so what did you do to fix this? @Scheph-96

**Comment by Scheph-96** [comment]
> so what did you do to fix this? @Scheph-96 

```
TextFormField(
      key: formFieldKey, // Add this field in the package source code
      controller: controller,
      decoration: fieldDecoration(hintText),
);
```

And set the variable "formFieldKey" as attribute of the class (`final GlobalKey<FormFieldState> formFieldKey`). After that you can use the field controller to validate and get the field content.

It's up to you to make the modification locally or make a pull request to update the project's main branch.

**Comment by dolapobabs** [comment]
Thanks @Scheph-96 It worked

**Comment by Scheph-96** [comment]
...

**Comment by marcaureln** [comment]
Thank you all, sorry for the delay. Better late than never. #321 merged.
