### ISSUE TITLE
countries is no longer use "String"

### ISSUE THREAD

**Issue by JmyW** [vanshg395/intl_phone_field#288]
Hi 
The v3.2.0 change the countries, no longer List＜String＞ but List＜Country＞. Could you teach me how to set countries on the version? countries: const ['TW', 'US'] ?? 

=========================================
IntlPhoneField(
                      controller: textCtlMobile,
                      focusNode: focusNodeMobile,
                      textInputAction: TextInputAction.next,
                      keyboardType: TextInputType.phone,
                      style: const TextStyle(color: MyColors.textColorBlack, fontSize: fontSz6),
                      initialCountryCode: initialCountryCd,
                      countries: const ['TW', 'US'],
... ...

**Comment by prkhrv** [comment]
Same issue here, let me know if you have figured it out

**Comment by JmyW** [comment]
Sorry I have not. My shorten solution is to keep on v3.1.0 :(
If you figure out, please let me know too. Thanks in advance.

**Comment by mbebs** [comment]
Anyone found a solution for this? I just need an example of how to list the countries.

**Comment by mbebs** [comment]
Please can someone help provide a simple solution
