### ISSUE TITLE
italy +39 not +41

### ISSUE THREAD

**Issue by studiozocaro** [vanshg395/intl_phone_field#290]
italy +39 not +41

flag: "🇮🇹",
    code: "IT",
    dialCode: "39",
    minLength: 9,
    maxLength: 10,

Number like +39 3511234567 or  +39 351123456

**Comment by MompiDevi** [comment]
I am facing the same issue as well, please provide an update on this.

**Comment by marcaureln** [comment]
Fixed by #293
