### ISSUE TITLE
Custom validator method not being executed when there's no interaction with the input whatsoever

### ISSUE THREAD

**Issue by augustogiavedoni** [vanshg395/intl_phone_field#292]
The custom validator method is only being executed inside the `onChanged` callback. The second option would be setting the `AutovalidateMode` to `always` and that's not the ideal scenario since you would like the validation logic to be executed after, for example, pressing a button. If that callback is not executed or the `AutovalidateMode` is not configured as `always`, the error message returned by the validator function is `null` (because it was never assigned a value since the custom validator method passed as a parameter was never called).

This validation logic should be revised specially for those cases where we need to ensure that the user enters a value inside the input, showing them an error message even when they haven't interacted with the input at all.

**Comment by abdimussa87** [comment]
I agree

**Comment by hashimsayed0** [comment]
I've created a PR [#298](https://github.com/vanshg395/intl_phone_field/pull/298) to fix this bug, it's working for me now, but I'm not sure if it broke something else, feel free to check and comment.

**Comment by hashimsayed0** [comment]
Hi @augiavedoni, thank you for testing and pointing out the bug. I've pushed a new commit in the PR that handles the bug you mentioned. validatorMessage is now set to null when the validator callback returns null. Please let me know if it fixes the issue.

**Comment by augiavedoni** [comment]
Hi there! Seems that is working fine now, I'm not seeing the error if I don't assign a callback to the validator attribute. When do you think this could be merged and released?

**Comment by hashimsayed0** [comment]
Hi @augiavedon 
Honestly, not sure. I do not have write access. I'm not sure if the maintainers got a chance to take a look.

**Comment by augiavedoni** [comment]
Hey @hashimsayed0! Do you think that maybe we should tag someone?

**Comment by hashimsayed0** [comment]
Hey @augiavedoni , sure. Hey @vanshg395 and @marcaureln , would you have some time to look into this issue and the corresponding PR #298 ? We believe the PR fixes the issue.

**Comment by fisforfaheem** [comment]
Please tell if this issue is fixed?? pelase release a hotfix

**Comment by kwsoftnet4** [comment]
not Fixed and when i enter valid length (8 numbers for example for kuwait) not show other errors in my custom validation (the other custom validation for example kuwaiti number start with 5 or 6 or 9).

![IntlPhoneField_1](https://github.com/vanshg395/intl_phone_field/assets/147930689/2fd01735-bd7d-4161-bf7d-a10fe266b1fd)
![IntlPhoneField_2](https://github.com/vanshg395/intl_phone_field/assets/147930689/6b9ef7a4-a1b0-4b9f-a546-27f1d2c7cff3)
![IntlPhoneField_3](https://github.com/vanshg395/intl_phone_field/assets/147930689/e460cbc9-8830-405e-9abd-8ffbe2a01d83)
