### ISSUE TITLE
initialCountryCode not working with Country Dial code, works with  ISO code only.

### ISSUE THREAD

**Issue by DevanshiGor** [vanshg395/intl_phone_field#294]
Thank you for amazing Package.

I am unable to set my Existing Country [specially 4 digit one] by using Country Dial code. Please solve it ASAP.
<img width="711" alt="Screenshot 2023-07-26 at 7 02 39 PM" src="https://github.com/vanshg395/intl_phone_field/assets/59550860/cef6c663-af05-4282-9bff-20487370320e">

**Comment by youssefsobhy1** [comment]
Any fixes available?
