### ISSUE TITLE
Empty Number Validator

### ISSUE THREAD

**Issue by ReeKid2002** [vanshg395/intl_phone_field#306]
Hi,
Is there any way to validate for empty number?

**Comment by TOMSLAUS** [comment]
Theres two ways to do this. Either write your own validator or just wrap it in Form widget and give it a key. 
When ever you want to validate the field do this

`onPressed: (){
   if (_formKey.currentState!.validate()) {
     //your function here if everything is okay.
   }
},`

**Comment by ReeKid2002** [comment]
@TOMSLAUS Not working for me
