### ISSUE TITLE
Wrong Italy code and problem with defining own countries

### ISSUE THREAD

**Issue by Oskar888** [vanshg395/intl_phone_field#312]
There is problem with Italy code, its defined as +41 = its wrong, it should be +39.
Also when I try to use own countries as parameter I have error like this:
<img width="1272" alt="Zrzut ekranu 2023-09-21 o 10 26 58" src="https://github.com/vanshg395/intl_phone_field/assets/117290293/fa11b35c-997b-462c-9fc3-8b005f43e1a3">

**Comment by collamaf** [comment]
I confirm. Any hope for a fix?

**Comment by ketanlogicloop** [comment]
⚠️ The package is deprecated and this repository is no longer maintained ⚠️
This is mentioned in [readme](https://github.com/vanshg395/intl_phone_field?tab=readme-ov-file#%EF%B8%8F-the-package-is-deprecated-and-this-repository-is-no-longer-maintained-%EF%B8%8F).
I found similar plugin on pub dev, which is [flutter_intl_phone_field](https://pub.dev/packages/flutter_intl_phone_field)
