### ISSUE TITLE
some times backspace doesn't work

### ISSUE THREAD

**Issue by ShohidulProgrammer** [vanshg395/intl_phone_field#4]
some times the phone field has some number which can not remove by backspace. but, doesn't print that value in onChanged method and unfortunately displays on the phone field.

eg, the field has and display some number: 66605
onChanged method print: only country code (coz, I remove the field number by pressing backspace)

**Comment by vanshg395** [comment]
Can u possible post a video of what you are facing?

**Comment by vanshg395** [comment]
I checked the code, can't replicate this error. If you face problem again pls post a video of the same.

Closing this Issue
