### ISSUE TITLE
No named parameter with the name 'child'

### ISSUE THREAD

**Issue by libindstme** [vanshg395/intl_phone_field#40]
/C:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/intl_phone_field-1.4.2/lib/intl_phone_field.dart:192:7: Error: No named parameter with the name 'child'.
      child: StatefulBuilder( 
^^^^

**Comment by VishvaRatnayake** [comment]
go inside 'package:intl_phone_field/intl_phone_field.dart'; and change line 192 child to builder:(context) =>

**Comment by vanshg395** [comment]
Fixed
