### ISSUE TITLE
GPLv3 -> LGPLv3?

### ISSUE THREAD

**Issue by jofas** [vanshg395/intl_phone_field#42]
Hi Vansh,

Looks like you did some great work with this library. Unfortunately, I've yet to test it because the GPLv3 is too restrictive for me. On that note, I'm hardly the only one that cannot use your library due to its strict licensing. Is there a concrete reason for you to have chosen the GPLv3? Aside from your noble free software goals, the license will only hurt this library's popularity, especially when there are other libraries out there solving the same problem (e.g. https://pub.dev/packages/intl_phone_number_input). Your library seems to have a nicer API though that's why I'm asking. Would you mind changing it to some less restrictive license like the LGPLv3, MIT or Apache v2? Thanks.

Kind regards,
Jonas

**Comment by vanshg395** [comment]
Sure, I will see through other licenses and update that if possible

**Comment by vanshg395** [comment]
Updated to MIT.

**Comment by jofas** [comment]
thanks!
