### ISSUE TITLE
restrict the countries to display in the list or  list only the countries which we have chosen beforehand

### ISSUE THREAD

**Issue by fofe00** [vanshg395/intl_phone_field#43]
imagine we have an application available only for 5 countries
we just need to list the 5 countries only and not all the countries

**Comment by 4mitabh** [comment]
A parameter that takes an array of country codes will be a good way to support this.

**Comment by 4mitabh** [comment]
Created a PR to support this:
https://github.com/vanshg395/intl_phone_field/pull/47

Please review and accept when you get a chance.

**Comment by vanshg395** [comment]
Fixed in #47
