### ISSUE TITLE
Sound null safety migration for Flutter 

### ISSUE THREAD

**Issue by SakhileMamba** [vanshg395/intl_phone_field#44]
Hello,

Please kindly migrate your package to support sound null safety in flutter.

**Comment by alberto-sf** [comment]
Hello @vanshg395!

I see that you have merged the migration. Could you please bump 2.0.0 to pub?

**Comment by vanshg395** [comment]
Surely will do by 1st April.

**Comment by BartusZak** [comment]
Thanks.

Looking forward to see that :)

**Comment by vanshg395** [comment]
Fixed and pushed
