### ISSUE TITLE
Automatically set max length of the input field based on the country selected

### ISSUE THREAD

**Issue by 4mitabh** [vanshg395/intl_phone_field#51]
I'll submit a PR.

**Comment by 4mitabh** [comment]
Submitted: https://github.com/vanshg395/intl_phone_field/pull/52

This will greatly help with the usability of the component.

**Comment by vanshg395** [comment]
Fixed in #52

**Comment by 4mitabh** [comment]
Thanks for accepting the PR.
Looking forward to the next release :)
