### ISSUE TITLE
BREAKING, Incorrect mobile required length 

### ISSUE THREAD

**Issue by yassinsameh** [vanshg395/intl_phone_field#54]
After the latest update the widget requires 9 digits for example  where a country needs 10 (Egypt) which how it was initially, i also want to remove the x/9 validator but to no avail.

**Comment by yassinsameh** [comment]
Version  intl_phone_field: ^2.0.0

**Comment by vanshg395** [comment]
You can change the validator field.

**Comment by yassinsameh** [comment]
I'm already trying to override it, as below. Could you please clarify how this can be done? 
```
  validator: (value) {
                                    if (value.isEmpty || value.length < 7) {
                                       return 'Please enter a valid number';
                                     }
                                        return null;
                                      },
```

**Comment by remymumoh** [comment]
how did you fix this?

**Comment by yassinsameh** [comment]
@remymumoh that was a while back, but i didn't fix it, i used another package instead. There are several alternatives you can find that are standard and reliable with their validations.
