### ISSUE TITLE
Incorrect phone number legnth for Pakistan

### ISSUE THREAD

**Issue by fai-ahm** [vanshg395/intl_phone_field#59]
If you select pakistan and then input number it allows 11 charachters when actually they should be 10.

Please fix this, this issue is also common with many other country lengths. If you fix these issues for all countries it will be the most popular package in pub.dev

**Comment by chinitadelrey** [comment]
The issue, and for #56, seems to be that it does not follow the libphonenumber package (library that keeps up to date formats for phone number formats from all countries). 

One possible point of potential contribution/improvement is to integrate the validation logic from this library into the existing package: https://github.com/nashfive/phone_number

**Comment by marcaureln** [comment]
Fixed, see #73
