### ISSUE TITLE
why max length of number should be 10?  I think 9 is the standard ?

### ISSUE THREAD

**Issue by ibrahimsebbane** [vanshg395/intl_phone_field#6]

**Comment by vanshg395** [comment]
Default is 10 for most countries but you can change it using maxLength argument.

**Comment by vanshg395** [comment]
Closing this now

**Comment by ibrahimsebbane** [comment]
Thanks

Le mer. 24 juin 2020 à 08:04, Vansh Goel <notifications@github.com> a
écrit :
