### ISSUE TITLE
Incorrect phone lenght for Mauritania

### ISSUE THREAD

**Issue by loullah-gti** [vanshg395/intl_phone_field#62]
Hello,
Thank you for your useful plugin.
I want to mention that the length of phone number in Mauritania **is** 8 **not** 7.
We cannot use the plugin without rectifying this.
Thank you.

**Comment by Coloud1** [comment]
Bosnia and Herzegovina also has a number length of 8 to 9 characters, and in the current version the maximum length is only 8
