### ISSUE TITLE
Incorrect phone number legnth for qatar

### ISSUE THREAD

**Issue by hashirventhodi** [vanshg395/intl_phone_field#69]
If you select Qatar and then input the number it allows 10 characters when actually they should be 8.

Please fix this, this issue is also common with many other country lengths.

**Comment by csedeepakyadav** [comment]
fixed. 
just use this

intl_phone_field:
    git:
      url: https://github.com/csedeepakyadav/intl_phone_field.git
      publish_to: none

**Comment by marcaureln** [comment]
Fixed, see #73
