### ISSUE TITLE
Erro on the new version

### ISSUE THREAD

**Issue by luizeduardotj** [vanshg395/intl_phone_field#7]
A receive this error on calling the IntlPhoneField():

```
The method 'copyWith' was called on null.
Receiver: null
Tried calling: copyWith(counter: Instance of 'SizedBox')
The relevant error-causing widget was
    IntlPhoneField 
``` 

I tried to call it a Column, Wrap and inside a simple container.

**Comment by vanshg395** [comment]
@luizeduardotj  Can u send the exact code segment you used for this field?

**Comment by vanshg395** [comment]
I am unable to recreate this issue, closing now.

Feel free to open again with sample code if you face the same problem.
