### ISSUE TITLE
Validation Logic is faulty

### ISSUE THREAD

**Issue by jahid-hasan-polash** [vanshg395/intl_phone_field#75]
The Validation logic doesn't check according to the selected country's max length. It compares to constant value 10. Which fails on several country selection validations. Thus auto validation doesn't work.
Here is the code from the package.

`validator = widget.autoValidate
        ? ((value) => value != null && value.length != 10
            ? 'Invalid Mobile Number'
            : null)
        : widget.validator;`

**Comment by marcaureln** [comment]
Thanks for reporting this issue. Fixed by e43848e. Will be available in the next package release.

**Comment by hanskokx** [comment]
This doesn't appear to be working, either.  Try to validate against This Uganda number: +256 726871593

**Comment by marcaureln** [comment]
I tried, and it worked well, you can update the package version and try again. If it doesn't work, I'll reopen the issue.

**Comment by hanskokx** [comment]
I’ve moved on from the project.  If I come across it again, I’ll be sure to update the ticket with my findings.

—
Hans Kokx
