### ISSUE TITLE
example in flutter web doesnot work

### ISSUE THREAD

**Issue by Yacine-Benali** [vanshg395/intl_phone_field#8]
run the example app in flutter web try to change the country

error:
> Error: setState() called after dispose(): _IntlPhoneFieldState#e0cb6(lifecycle state: defunct, not mounted)
> This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
> The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
> This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

flutter version:

> Flutter 1.20.0-3.0.pre.63 • channel master • https://github.com/flutter/flutter.git
> Framework • revision 1e6e7150f3 (6 days ago) • 2020-06-26 12:01:59 +0800
> Engine • revision 22b099bc63
> Tools • Dart 2.9.0 (build 2.9.0-19.0.dev ea87c9b01a)

**Comment by vanshg395** [comment]
It works fine on **Beta** branch. Please do not use master branch because it is very unstable.

**Comment by Yacine-Benali** [comment]
alright thanks
