### ISSUE TITLE
Add the ability to disable the country list dropdown

### ISSUE THREAD

**Issue by indiana-dev** [vanshg395/intl_phone_field#82]
It could be great to have a similar property to `readOnly` or `enabled` for the country list dropdown.
I need the user to enter its phone number, and once validated I need to keep the IntlPhoneField widget but without the ability to change it. So I disable the textfield, but I can't disable the country list drop down, even if I hide the cursor icon using `showDropdownIcon`=false.

As a quick fix I tried to change the `countries` array after validating the phone number and set it to one unique value (the currently selected country) so even if the user access the dropdown he won't have the ability to change the country. 
Unfortunately, this doesn't seems to work as the initial value of `countries` seems to be permanent, even when updating it in a stateful widget.

**Comment by marcaureln** [comment]
Thanks for your feedback, there is no doubt that when set to `false`, `enabled` must deactivate the dropdown button as well. I'd just implemented it (see f9fc8ca). You'll be able to do it in the next release of the package or if you need to use this feature now, you can see how to do it [here](https://dart.dev/tools/pub/dependencies#git-packages). Until next time, enjoy!
