### ISSUE TITLE
Flag and number don't update according to initial value

### ISSUE THREAD

**Issue by aris-1** [vanshg395/intl_phone_field#83]
If we provide an initial value or a controller with a text prepopulated, then the flag and number don't update according to the provided value.

For example if initValue="+33123456789"
the flag should be the French one and the displayed number should be "123456789".

Instead it displays the US flag or whatever is the initialCountryCode and the displayed number remains "+33123456789"

**Comment by marcaureln** [comment]
Hi, the `initValue` should be set to the phone number itself, "123456789" in your case. And, for the country flag, you should use `initialCountryCode` and set it to "FR"

**Comment by aris-1** [comment]
I wrote a function that you could use, to automate the procedure.

`
 if (initValue.isNotEmpty){
      var ret=getCountry(initValue);
      if (ret[0]!=null){
        initValue=ret[1];
        initialCountryCode=ret[0];
      }
    }


getCountry(String phone) {//phone must start with +
  var index=-1,found,dialCode,isoCode;
   for (var i = 4; i > 1; i--) {
     dialCode=int.tryParse(phone.substring(1,i)) ?? -1;
     try {
       index = countries.indexWhere((y) => y["dial_code"] == dialCode);
     } catch (e) {
     }
     if (index>-1){
       break;
     }
  }
   if (index>-1){
     found=countries[index];
     isoCode=found["code"];
     dialCode=found["dial_code"];
     phone=phone.replaceFirst("+$dialCode","");
   }
  return  [isoCode,phone,dialCode];
}`

**Comment by marcaureln** [comment]
Thanks for the code snippet, I'll keep it warm and see how to integrate it in the package or share it in a coming FAQ section for the package.

**Comment by levent-kantaroglu** [comment]
It would be useful feature, because plenty of databases keeping phone numbers with digits not letters.
