### ISSUE TITLE
Check Max Length of Phone Number of Related Country

### ISSUE THREAD

**Issue by ardadizdaroglu** [vanshg395/intl_phone_field#86]
Hello,

Firstly, I wrote on Stackoverflow ([link](https://stackoverflow.com/questions/68329015/flutter-international-phone-field-check-max-length-of-phone-number-of-relate)) but didn't get answer so I wanted to write here.

You added maximum length of phone numbers of several countries in 2.0.1. So as I showed with red arrow on my picture in link, there is a length field on bottom right of TextInput.

So my question is, for example for this picture, how can I check that 10/10 numbers character entered?

**Comment by ardadizdaroglu** [comment]
thank you so much ! but I suggest you to change this thing to something like `phone.getMaxLength`

**Comment by marcaureln** [comment]
Great, I take note of it
