### ISSUE TITLE
Formatting a Phone Number

### ISSUE THREAD

**Issue by Sozaro** [vanshg395/intl_phone_field#89]
how can I format the numbers?
like an example with SA number
+966555555555
I want it to be
+966 55 555 5555
when the user writing the number.

**Comment by marcaureln** [comment]
Sorry, but you can't do that with the current version of the package.

**Comment by shabeenabarde** [comment]
> Sorry, but you can't do that with the current version of the package.

Does any of the previous version have it?!

**Comment by marcaureln** [comment]
Nope, sorry if I confuse you, what I meant was that the feature can be added in future version of the package!
