### ISSUE TITLE
prefill number (initial value)

### ISSUE THREAD

**Issue by aliasgarlabs** [vanshg395/intl_phone_field#9]
Feature request: Ability to prefill the number by using an API like the one in TextFormField (initialValue).

Used case: The requirement is when the number entered earlier can be edited. 

If this is not in works already, I am happy to submit a PR. 

Thanks!

**Comment by vanshg395** [comment]
well, this feature can be quite usefull. Though it can be implemented using controllers, but still if you want it to be available like initialValue argument, you can send a PR.

**Comment by vanshg395** [comment]
Added.

**Comment by Technorocker** [comment]
This feature was added but I'm having one hell of a time  trying to populate this value when I load my widget. I'm grabbing the mobile number successfully using the mobile_number plugin and when I try to use that variable with the number store it doesnt show up. 

Having said that when I do a restart in vscode the widget updates and the number fills in. I have then implemented the use of GetX using obs on the value and Obx method wrapped around intlPhoneField but its still not filling the input box.

Here is the widget portion...

```
child: Obx(
              () => IntlPhoneField(
                dropdownIcon: Icon(
                  Icons.arrow_drop_down,
                  color: Theme.of(context).colorScheme.secondary,
                ),
                //controller: phoneController,
                onChanged: (phone) {
                  print(phone.completeNumber);
                  print(phone.countryCode);
                  print(phone.number);
                },
                cursorColor: Theme.of(context).colorScheme.secondary,
                cursorWidth: 3.sp,
                keyboardType: TextInputType.number,
                **initialValue: permController.coreMobileNumber.value,**
                dropdownTextStyle: TextStyle(
                    color: Theme.of(context).colorScheme.secondary,
                    fontWeight: FontWeight.bold,
                    fontSize: 15.sp,
                    letterSpacing: 1.2.sp),
```
 and here is the method I'm using to grab the mobile number...

```
  final coreMobileNumber = ''.obs;
  Future<void> getMobileNumber() async {
    final completeNumber = await MobileNumber.mobileNumber;
    var properNumber = '';
    if (completeNumber != null) {
      properNumber = completeNumber.substring(completeNumber.length - 10);
    }
    coreMobileNumber.value = properNumber;
    Storage.saveValue('mobileNumber', properNumber);
  }
```
any help using this feature would be much appreciated

**Comment by funyin** [comment]
Same here.
