### ISSUE TITLE
Country dropdown button and text field are not aligned

### ISSUE THREAD

**Issue by masteradit** [vanshg395/intl_phone_field#91]
According to the image shown in README.md, the widget should look like this:

<img src="https://github.com/vanshg395/intl_phone_field/blob/master/1.png?raw=true" height="500px">

However, due to the `maxLength` property, it looks like this:
![image](https://user-images.githubusercontent.com/39951503/126878314-d8099412-1dcc-4bc1-8a8f-578cc3e6a303.png)

Is there any way to fix this?

**Comment by marcaureln** [comment]
Hello, you can fix this by setting `counterText` value of the decoration property to `''` (empty quotes) but this will obviously hide the counter.
```
IntlPhoneField(
                  ...
                  decoration: InputDecoration(
                    ...
                    counterText: '',
                  ),
                ),
```

**Comment by fvisticot** [comment]
I have still the issue:
Any fix / workaround on that ?

![IMG_ABC797EE8FB7-1](https://user-images.githubusercontent.com/153679/214968241-a7202141-27e1-4c98-ae32-482e4ef1df19.jpeg)

**Comment by RonBis** [comment]
> I have still the issue: Any fix / workaround on that ?
> 
> ![IMG_ABC797EE8FB7-1](https://user-images.githubusercontent.com/153679/214968241-a7202141-27e1-4c98-ae32-482e4ef1df19.jpeg)

+1
