### ISSUE TITLE
I can't change the value of "initialCountryCode" with set state

### ISSUE THREAD

**Issue by mohammedsaidm** [vanshg395/intl_phone_field#94]
I do everything as you mentioned below.

https://github.com/vanshg395/intl_phone_field/issues/21#issuecomment-703374926

"If you set initialCountryCode to a dynamic variable and then change the value of that variable inside setState, it will work. It worked for me where I was getting countryCode from IP Address."

**Comment by mohammedsaidm** [comment]
@aliasgarlabs @4mitabh @ZaharL @pmatheus please help.

**Comment by aliasgarlabs** [comment]
@mohammedsaidm  Please share your code and reproduction steps.

**Comment by debovitch** [comment]
You can add a key: UniqueKey() to your IntlPhoneField widget, it will force to pass in the initState again.
