### ISSUE TITLE
color issue for validation text

### ISSUE THREAD

**Issue by tanvir5230** [vanshg395/intl_phone_field#95]
Can't change the color of the validation text (0/8, 0/10 etc.)

**Comment by marcaureln** [comment]
Simply add a TextStyle to the counterStyle property of the InputDecoration object of the IntlPhoneField decoration property. 

This is an example, where the counter text will be displayed in red : 

IntlPhoneField(
   decoration: InputDecoration(
        counterStyle: TextStyle(color: Colors.red),
        ...
   ),
   ...
),
