### ISSUE TITLE
Add padding in DropDownButton when hide DropdownIcon

### ISSUE THREAD

**Issue by TamNguyen8021** [vanshg395/intl_phone_field#97]
When hiding the DropDownIcon, the UI looks like this:
![image](https://user-images.githubusercontent.com/56307360/127972075-cd80773c-c15e-4d24-98de-c6c47ec39a02.png)

It looks very ugly as the flag icon does not have any padding on the left, and I can't find any way to fix this.
I also want to edit the country code text style, like make it smaller. Is there any way to do this?

**Comment by MikeMudimba** [comment]
TamNguyen8021 try adding TextFieldContainer

**Comment by marcaureln** [comment]
In the 3.0.0 package version, you can now wrap your flag button with `flagsButtonPadding`
