### ISSUE TITLE
When put IntlPhoneField() inside Stack(), the field is uneditable

### ISSUE THREAD

**Issue by TamNguyen8021** [vanshg395/intl_phone_field#99]
I have a background on my screen, so I put IntlPhoneField() inside a Stack(), but then the field is uneditable. At first I thought it's my bug, but when I replace the Stack() with Column(), the field can be edited again. So this is a bug.

**Comment by marcaureln** [comment]
Hey, can you please share part of your code to reproduce the bug (and by the way the fix you find too)

**Comment by TamNguyen8021** [comment]
I tested it again, this is not your bug, so I will close this issue. Sorry about that.
